let name1="Fazil";
let name2="Hari";
let name3="Vishwa";
let school1="Crescent Matriculation School";
let school2="Holy Angles School";
let school3="Sunbeam School";
let grade1="B";
let grade2="A";
let grade3="A";
let section1="a";
let section2="b";
let section3="c";
let rollno1=1001;
let rollno2=1002;
let rollno3=1003;
let marks1=70;
let marks2=90;
let marks3=80;
console.log(name1,school1,grade1,section1,rollno1,marks1);
console.log(name2,school2,grade2,section2,rollno2,marks2);
console.log(name3,school3,grade3,section3,rollno3,marks3);